<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { http, problemMessage } from '@/api/http'
interface PublicAsset { name: string; category: string; publicDescription?: string; publicCode: string; zoneName?: string; longitude?: number; latitude?: number; facility?: Record<string, string | number>; plant?: Record<string, string | number> }
const route = useRoute(); const router = useRouter(); const asset = ref<PublicAsset>(); const error = ref(''); const loading = ref(true)
async function load(): Promise<void> { loading.value = true; try { asset.value = (await http.get<PublicAsset>(`/public/assets/${route.params.publicCode}`)).data } catch (e) { error.value = problemMessage(e) } finally { loading.value = false } }
onMounted(() => { void load() })
</script>
<template><div class="public-asset"><el-button text type="primary" @click="router.push('/visitor')">← 返回公园服务</el-button><el-skeleton v-if="loading" :rows="8" animated /><el-result v-else-if="error" icon="error" title="公开资产不存在或不可查看" :sub-title="error" /><section v-else-if="asset" class="asset-card"><p>PUBLIC ASSET · {{ asset.publicCode }}</p><h1>{{ asset.name }}</h1><el-tag>{{ asset.category }}</el-tag><div class="asset-description">{{ asset.publicDescription || '该资产暂无公开介绍。' }}</div><div class="asset-info"><div><span>所在区域</span><b>{{ asset.zoneName || '园内公共区域' }}</b></div><div><span>位置</span><b>{{ asset.longitude ?? '—' }}, {{ asset.latitude ?? '—' }}</b></div></div><div v-if="asset.facility || asset.plant" class="public-data"><div v-for="(value,key) in (asset.facility || asset.plant)" :key="String(key)"><span>{{ key }}</span><b>{{ value }}</b></div></div><small>本页仅提供游客公开资料，不展示内部设备、维护记录、事件或工单信息。</small></section></div></template>
<style scoped>.public-asset { max-width:850px; margin:0 auto; padding:58px 0 90px; }.asset-card { margin-top:18px; padding:40px; border:1px solid #e2ece7; border-radius:16px; background:linear-gradient(145deg,#fff,#f0f8f3); }.asset-card > p { color:#439478; font-size:11px; letter-spacing:.13em; }.asset-card h1 { margin:10px 0 16px; color:#285042; font-size:35px; }.asset-description { margin:28px 0; color:#5a7269; font-size:16px; line-height:1.8; }.asset-info { display:grid; grid-template-columns:1fr 1fr; gap:10px; }.asset-info div,.public-data div { padding:13px; border-radius:8px; background:#fff; }.asset-info span,.asset-info b,.public-data span,.public-data b { display:block; }.asset-info span,.public-data span { color:#7a8b85; font-size:11px; }.asset-info b,.public-data b { margin-top:4px; color:#3b5f54; font-size:13px; }.public-data { display:flex; flex-wrap:wrap; gap:10px; margin-top:10px; }.asset-card small { display:block; margin-top:25px; color:#82918c; font-size:11px; }</style>
