<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getList, getPage, post, put } from '@/api/resources'
import { problemMessage } from '@/api/http'
import { useSessionStore } from '@/stores/session'
import ProductionHint from '@/components/ProductionHint.vue'
import StatusTag from '@/components/StatusTag.vue'
import { formatDate } from '@/utils/format'

interface Platform { id: string; name: string; enabled: boolean; forceFailure?: boolean }
interface Message { id: string; platformName?: string; kind: string; status: string; attempts?: number; createdAt?: string; detail?: string }
const session = useSessionStore(); const isAdmin = () => session.hasAnyRole(['Administrator']); const platforms = ref<Platform[]>([]); const messages = ref<Message[]>([]); const loading = ref(true); const error = ref(''); const syncing = ref('')
async function load(): Promise<void> { loading.value = true; error.value = ''; try { const [platformData, messageData] = await Promise.all([getList<Platform>('/integrations/platforms'), getPage<Message>('/integrations/messages')]); platforms.value = platformData; messages.value = messageData.items } catch (e) { error.value = problemMessage(e) } finally { loading.value = false } }
async function update(item: Platform): Promise<void> { try { await put(`/integrations/platforms/${item.id}`, { enabled: item.enabled, forceFailure: item.forceFailure }); ElMessage.success('模拟平台状态已更新。') } catch (e) { ElMessage.error(problemMessage(e)); await load() } }
async function sync(platform: Platform, kind: 'Assets' | 'VisitorCount' | 'VideoMetadata' | 'PublicCodes'): Promise<void> { syncing.value = `${platform.id}-${kind}`; try { await post('/integrations/sync', { platformId: platform.id, kind }); await load(); ElMessage.success('本地模拟同步任务已生成，未发送至外部网络。') } catch (e) { ElMessage.error(problemMessage(e)) } finally { syncing.value = '' } }
async function retry(item: Message): Promise<void> { try { await post(`/integrations/messages/${item.id}/retry`); await load(); ElMessage.success('已请求本地重试。') } catch (e) { ElMessage.error(problemMessage(e)) } }
onMounted(() => { void load() })
</script>
<template><div class="page"><div class="page-heading"><div><h1>外部平台协同</h1><p>五类平台使用共享本地模拟适配器，仅保留业务映射与回执日志。</p></div><el-button @click="load">刷新日志</el-button></div><el-alert v-if="error" type="error" :title="error" :closable="false" /><section class="platform-grid" v-loading="loading"><article v-for="platform in platforms" :key="platform.id" class="surface platform-card"><div><span>本地模拟适配器</span><h3>{{ platform.name }}</h3><p>{{ platform.enabled ? '已启用本地模拟回执' : '已停用，不会生成同步回执' }}</p></div><el-switch v-if="isAdmin()" v-model="platform.enabled" active-text="模拟启用" inactive-text="已停用" @change="update(platform)" /><el-tag v-else :type="platform.enabled ? 'success' : 'info'">{{ platform.enabled ? '模拟启用' : '已停用' }}</el-tag><div v-if="isAdmin()" class="failure"><el-checkbox v-model="platform.forceFailure" @change="update(platform)">注入模拟失败</el-checkbox></div><div class="sync-actions"><el-button size="small" :loading="syncing === `${platform.id}-Assets`" @click="sync(platform, 'Assets')">资产</el-button><el-button size="small" :loading="syncing === `${platform.id}-VisitorCount`" @click="sync(platform, 'VisitorCount')">客流</el-button><el-button size="small" :loading="syncing === `${platform.id}-VideoMetadata`" @click="sync(platform, 'VideoMetadata')">视频元数据</el-button><el-button size="small" :loading="syncing === `${platform.id}-PublicCodes`" @click="sync(platform, 'PublicCodes')">公开物码</el-button></div></article><el-empty v-if="!loading && !platforms.length" description="暂无平台配置" /></section><section class="surface table-panel"><div class="data-title">模拟同步消息</div><p class="muted">成功只表示本地适配器生成回执，未发送外部网络；失败可按服务端退避规则或人工重试。</p><el-table :data="messages" empty-text="暂无同步消息"><el-table-column prop="platformName" label="目标平台" min-width="180" /><el-table-column prop="kind" label="业务类型" width="140" /><el-table-column label="状态" width="150"><template #default="scope"><StatusTag :status="scope.row.status" /></template></el-table-column><el-table-column prop="attempts" label="尝试次数" width="100" /><el-table-column prop="detail" label="本地回执" min-width="220" /><el-table-column label="创建时间" width="180"><template #default="scope">{{ formatDate(scope.row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="100"><template #default="scope"><el-button link type="primary" :disabled="scope.row.status !== 'Failed'" @click="retry(scope.row)">人工重试</el-button></template></el-table-column></el-table></section><ProductionHint topic="platforms" /></div></template>
<style scoped>.platform-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:16px; }.platform-card { padding:18px; }.platform-card > div:first-child { min-height:82px; }.platform-card span { color:#789087; font-size:11px; }.platform-card h3 { margin:7px 0; color:#2b5147; font-size:16px; }.platform-card p { margin:0; color:#70817b; font-size:12px; }.failure { margin:14px 0; }.sync-actions { display:flex; flex-wrap:wrap; gap:6px; }.table-panel { margin-top:18px; padding:18px; }.table-panel .data-title { margin-bottom:4px; }</style>
