<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { http, problemMessage } from '@/api/http'
import MetricChart from '@/components/MetricChart.vue'
import ParkMap, { type MapAsset, type MapLayer } from '@/components/ParkMap.vue'
import SourceBadge from '@/components/SourceBadge.vue'
import { formatDate, formatNumber } from '@/utils/format'
import type { Metric } from '@/types/domain'

interface Summary { parkName: string; generatedAt: string; simulationEnabled: boolean; visitors: { inside: number; todayIn: number; todayOut: number; source: 'Seed' | 'Simulation' | 'Manual' }; devices: { fresh: number; stale: number }; alerts: number; events: number; workOrders?: { active: number; open: number; pendingReview: number; completed: number } | number; workOrderSummary?: { active: number; open: number; pendingReview: number; completed: number }; metrics: Metric[]; eco?: { score?: number } }
const activeOrders = () => { const counts = typeof summary.value?.workOrders === 'object' ? summary.value.workOrders : summary.value?.workOrderSummary; return (counts?.open ?? 0) + (counts?.pendingReview ?? 0) }
const summary = ref<Summary>(); const trends = ref<{ time: string; value: number }[]>([]); const map = ref<{ layers: MapLayer[]; assets: MapAsset[] }>({ layers: [], assets: [] }); const error = ref(''); let timer: number | undefined
async function load(): Promise<void> { try { const [s, t, m] = await Promise.all([http.get<Summary>('/overview/summary'), http.get<{ time: string; value: number }[]>('/overview/trends', { params: { metricCode: 'noise', hours: 24 } }), http.get<{ layers: MapLayer[]; assets: MapAsset[] }>('/public/map')]); summary.value = s.data; trends.value = t.data; map.value = m.data } catch (e) { error.value = problemMessage(e) } }
onMounted(() => { void load(); timer = window.setInterval(() => { if (!document.hidden) void load() }, 10_000) }); onBeforeUnmount(() => window.clearInterval(timer))
</script>
<template><main class="screen"><header><div><p>SMART PARK COMMAND CENTER</p><h1>{{ summary?.parkName || '智慧公园运行指挥中心' }}</h1></div><div class="screen-time"><b>{{ formatDate(summary?.generatedAt) }}</b><span>{{ summary?.simulationEnabled ? '模拟器运行中（演示）' : '模拟器未开启（演示）' }}</span></div></header><el-alert v-if="error" type="error" :closable="false" :title="error" /><div v-if="summary" class="screen-grid"><section class="screen-card statistics"><div class="card-title">实时态势 <SourceBadge :source="summary.visitors.source" /></div><div class="big-number"><strong>{{ formatNumber(summary.visitors.inside) }}</strong><span>在园人数</span></div><div class="split"><span>今日入园 <b>{{ summary.visitors.todayIn }}</b></span><span>今日出园 <b>{{ summary.visitors.todayOut }}</b></span></div></section><section class="screen-card trend"><div class="card-title">噪声趋势 <small>后端聚合 / 24H</small></div><MetricChart :points="trends" unit="dB" color="#53d5e7" /></section><section class="screen-card alerts"><div class="card-title">处置队列</div><div class="queue"><div><span>未恢复告警</span><b class="amber">{{ summary.alerts }}</b></div><div><span>处置中事件</span><b class="red">{{ summary.events }}</b></div><div><span>待办工单</span><b class="blue">{{ activeOrders() }}</b></div></div></section><section class="screen-card map-card"><div class="card-title">公园一张图 <small>本地离线数据</small></div><ParkMap :layers="map.layers" :assets="map.assets" /></section><section class="screen-card monitors"><div class="card-title">关键环境指标</div><div class="metric-list"><div v-for="metric in summary.metrics.slice(0, 7)" :key="`${metric.deviceId}-${metric.metricCode}`"><span>{{ metric.metricCode }}</span><b>{{ formatNumber(metric.value, 1) }} <small>{{ metric.unit }}</small></b><SourceBadge :source="metric.source" /></div></div></section><section class="screen-card eco"><div class="card-title">生态环境综合分 <small>演示口径</small></div><strong>{{ formatNumber(summary.eco?.score, 1) }}</strong><p>A=clamp(100(1-PM2.5/150))<br>N=… · W=100DO/8<br>E=.4A+.3N+.3W</p><span>数据不足时不补零，非官方生态评价。</span></section></div></main></template>
<style scoped>
.screen { min-height:100vh; padding:25px 32px 32px; color:#d7f1ef; background:radial-gradient(circle at 50% 0,#124e59,#071b27 53%); }.screen header { display:flex; justify-content:space-between; align-items:end; padding:0 4px 22px; }.screen header p { margin:0 0 5px; color:#53c6c6; font-size:11px; letter-spacing:.16em; }.screen h1 { margin:0; color:#f0ffff; letter-spacing:.06em; font-size:28px; }.screen-time { text-align:right; font-size:12px; }.screen-time b,.screen-time span { display:block; }.screen-time span { margin-top:5px; color:#e9bc5d; }.screen-grid { display:grid; grid-template-columns:1.05fr 1.6fr 1.05fr; grid-template-rows:215px 430px; gap:15px; }.screen-card { min-width:0; overflow:hidden; padding:16px; border:1px solid rgba(103,220,218,.17); background:rgba(11,45,58,.72); box-shadow:inset 0 1px rgba(205,255,252,.04); }.card-title { display:flex; align-items:center; justify-content:space-between; color:#c6edeb; font-size:13px; letter-spacing:.04em; }.card-title small { color:#72a5aa; font-size:11px; }.big-number { display:flex; align-items:baseline; gap:10px; margin:23px 0; }.big-number strong { color:#81f0c8; font-size:53px; line-height:1; }.big-number span { color:#8eafb2; font-size:13px; }.split { display:flex; gap:16px; color:#83a8ab; font-size:12px; }.split b { color:#d0eeee; }.trend :deep(.metric-chart) { height:175px; }.alerts .queue { margin-top:12px; }.queue div { display:flex; align-items:center; justify-content:space-between; padding:12px 2px; border-bottom:1px solid rgba(153,223,219,.12); color:#8cb2b5; font-size:12px; }.queue b { font-size:25px; }.amber { color:#e6bd63; }.red { color:#f17c76; }.blue { color:#6bbad3; }.map-card { grid-column:span 2; }.map-card :deep(.park-map) { margin-top:12px; height:365px; filter:saturate(.75) brightness(.78); }.monitors { grid-column:3; grid-row:2; }.metric-list { margin-top:8px; }.metric-list div { display:grid; grid-template-columns:1fr auto auto; align-items:center; gap:8px; padding:8px 0; border-bottom:1px solid rgba(144,224,219,.12); font-size:11px; color:#8ab0b2; }.metric-list b { color:#e1ffff; font-size:15px; }.metric-list small { color:#75a3a5; font-size:10px; }.eco { position:relative; }.eco strong { display:block; margin:27px 0 15px; font-size:58px; color:#77e0b7; }.eco p { color:#94bdba; font-family:monospace; line-height:1.8; font-size:12px; }.eco span { position:absolute; bottom:16px; color:#72969a; font-size:10px; }
</style>
